name: Code Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Code Review Bot
        uses: kurtyoon/pr-review-bot@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          llm_provider: openai
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          pr_number: ${{ github.event.pull_request.number }}
